project_id = "ykwiqymksnndugphhgmc"

[functions.telegram-bot]
verify_jwt = false

[functions.model-bot]
verify_jwt = false

[functions.onlymonster-api]
verify_jwt = false

[functions.send-error-notification]
verify_jwt = false
